[cosmic-ray]
module-path = "src/core"
timeout = 60
excluded-modules = ["tests"]

# --- ESTA É A CORREÇÃO ---
# 1. Removemos o comando 'env' (que é do Linux)
# 2. Adicionamos "-m django_db" para rodar APENAS os 10 testes
#    que têm permissão para acessar o banco de dados.
test-command = "pytest --ds=config.settings -q --disable-warnings -m django_db"

[cosmic-ray.cloning]
method = "copy"

[cosmic-ray.distributor]
name = "local"